{{- if .Values.automationController.admin_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "ansible-automation-controller-custom-admin-password"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ansible-automation-controller
    app.kubernetes.io/part-of: ansible-automation-controller
type: Opaque
data:
  password: {{ .Values.automationController.admin_password | b64enc | quote }}
{{- end }}
