{{- if .Values.automationController.ldap_cacert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-cacert
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ansible-automation-controller
    app.kubernetes.io/part-of: ansible-automation-controller
type: Opaque
data:
  ldap-ca.crt: {{ .Values.automationController.ldap_cacert | b64enc | quote }}
{{- end }}
