---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_final:
    - RUN pip3 install --upgrade pip setuptools
  append_final:
    - RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 3
    - RUN dnf install -y openshift-clients
