---
- name: perform setup tasks for AAP credentials, OCP credentials, S3 initialization, and OpenShift AI
  hosts: localhost

  tasks:
  - name: ensure a creds.yml file exists with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY defined
    ansible.builtin.file:
      path: creds.yml
      state: present

  - name: install prerequisite operators with Helm
    community.kubernetes.helm:
      name: test
      chart_ref: files/operators-installer/Chart.yaml
      release_namespace: gudemo
      wait: true # waits until all services are up with minimal config to mark successful

  - name: install OpenShift Data Foundations operator to host s3
    ansible.builtin.command: oc apply -f files/ODF-operator/sub.yml
       
  - name: carve out s3 bucket for Automation Hub
    amazon.aws.s3_bucket:
      access_key: {{ aws_access_key_id }}
      acl: public-read-write

  - name: install AAP operator
    ansible.builtin.command: oc apply -f files/AAP-operator/sub.yml 

  - name: set up Automation Controller
    ansible.builtin.command: oc apply -f files/AAP-operator/AutomationController/automationcontroller-example.yml

  - name: set up Automation Hub
    ansible.builtin.command: oc apply -f files/AAP-operator/AutomationHub/automationhub-example.yml

  - name: set up EDA Controller
    ansible.builtin.command: oc apply -f files/AAP-operator/EDA/edacontroller-example.yml

  - name: set up RHODS Operator
    ansible.builtin.command: oc apply -f files/RHODS-operator/sub.yml

  - name: install OpenShift AI operator
    ansible.builtin.command: oc apply -f files/RHOAI-operator/sub.yml
    
  - name: wait for OpenShift AI operator to be ready
    ansible.builtin.k8s_info:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: rhods-operator
      namespace: openshift-operators
    register: csv_status
    until: csv_status.resources[0].status.phase == "Succeeded"
    retries: 30
    delay: 10

  - name: create OpenShift AI instance
    ansible.builtin.command: oc apply -f files/RHOAI-operator/instance.yml

  - name: wait for OpenShift AI instance to be ready
    ansible.builtin.k8s_info:
      api_version: rhods.redhat.com/v1
      kind: RhodsInstance
      name: rhods
      namespace: redhat-ods-operator
    register: rhods_status
    until: rhods_status.resources[0].status.phase == "Ready"
    retries: 60
    delay: 10

  - name: set up workloads on the platform
    ansible.builtin.command: oc apply -f /files/workload/workload.yml
