---
- name: perform setup tasks for AAP credentials, OCP credentials, and S3 initialization
  hosts: localhost

  tasks:
  - name: ensure a creds.yml file exists with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY defined
    ansible.builtin.file:
      path: creds.yml
      state: present

  - name: install OpenShift Data Foundations operator to host s3
    ansible.builtin.command: oc apply -f files/ODF-operator/sub.yml
       
	
  - name: carve out s3 bucket for Automation Hub
    amazon.aws.s3_bucket:
      access_key: {{ aws_access_key_id }}
      acl: public-read-write

  - name: install AAP operator
    ansible.builtin.command: oc apply -f files/AAP-operator/sub.yml 

  - name: set up Automation Controller
    ansible.builtin.command: oc apply -f files/AAP-operator/AutomationController/file.yml

  - name: set up Automation Hub
    ansible.builtin.command: oc apply -f files/AAP-operator/AutomationHub/file.yml

  - name: set up EDA Controller
    ansible.builtin.command: oc apply -f files/AAP-operator/EDA/file.yml

  - name: set up RHODS Operator
    ansible.builtin.command: oc apply -f files/RHODS-operator/sub.yml
