---
collections:
  - name: awx.awx
# version: <acceptable version range of the collection>
# source: <URL of Galaxy server or private automation hub>
  - name: amazon.aws
  - name: infra.aap_utilities
  - name: infra.ee_utilities
  - name: containers.podman
  - name: ansible.builtin
  - name: ansible.utils
  - name: ansible.posix
  - name: ansible.network
  - name: google.cloud
  - name: azure.azcollection
  - name: redhat.openshift
  - name: redhat.sso
  - name: redhat.eap
  - name: redhat.data_grid
  - name: redhat.amq_broker
  - name: redhat.scm
  - name: ansible.controller
  - name: ansible.windows
  - name: cloud.terraform
  - name: kubernetes.core
  - name: redhat.jws
  - name: redhat.jbcs
  - name: redhat.rhel_idm
  - name: redhat.rhel_system_roles
  - name: redhat.runtimes_common
  - name: redhat.satellite
  - name: redhat.satellite_operations
  - name: servicenow.itsm
  - name: vmware.vmware_rest 
