---
collections:
  - name: awx.awx
    version: ">=21.14.0"
  - name: amazon.aws
    version: ">=6.0.0"
  - name: containers.podman
    version: ">=1.10.1"
  - name: ansible.utils
    version: ">=2.10.0"
  - name: ansible.posix
    version: ">=1.5.4"
  - name: redhat.openshift
    version: ">=2.3.0"
  - name: ansible.controller
    version: ">=4.5.0"
  - name: kubernetes.core
    version: ">=2.4.0"
