{{- /*
Create one RoleBinding per operator that needs to be approved.
NOTE: used to do this one per namespace, but that has issues if using this chart as dependency in multiple parent charts that are all
installing into the same namespace. So while this creates more resources, it allows for more robust use.
*/}}
{{- range .Values.operators }}
{{- if eq .installPlanApproval "Manual" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "operators-installer.approverName" . }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
  annotations:
    {{- if $.Values.approveManualInstallPlanViaHook }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
    {{- else }}
    argocd.argoproj.io/sync-wave: "-30"
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operators-installer.approverName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operators-installer.approverName" . }}
{{- end }}
{{- end }}
