apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: example-controller
  namespace: aap
spec:
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: false
  ingress_type: Route
  loadbalancer_port: 80
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  projects_storage_access_mode: ReadWriteMany
  projects_persistence: true
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  nodeport_port: 30080
  resource_requirements:
    nginx:
      limits:
        cpu: 500m
        memory: 768Mi
      requests:
        cpu: 100m
        memory: 256Mi
    web:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
    task:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
    redis:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    postgres:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi
